### ISSUE TITLE
Question: Powering the Wifi Thermostat 

### ISSUE THREAD

**Issue by kunalshetye** [vitzaoral/esp32_thermostat#1]
Hi, sorry for the silly question but how is the wifi thermostat powered?

Does the thermostat siphon off power from the 220v (old thermostat) or is it externally powered?

**Comment by vitzaoral** [comment]
Hi, sorry for late answer. Yes, exactly as you write, project is powered by the old 220V thermostat. I am using [this 220V to 5V module](https://www.aliexpress.com/item/Hi-Link-ac-dc-power-module-5v-3w-220v-isolated-ac-dc-converter/32360232521.html). So there are four cables between old and new thermostat. Two for power supply (220V) and two for relay module (with switch on and off heating).

**Comment by kunalshetye** [comment]
@vitzaoral if it is not too much to ask, would it possible to update the diagram to reflect the actual wiring after this was attached to the existing thermostat? 🙇

**Comment by vitzaoral** [comment]
Hello, I [updated wiring diagram](https://github.com/vitzaoral/esp32_thermostat/blob/master/schema/schema.png). It's no big deal, just connect 220V to HiLink module which converts 220V to 5V, or you can go safer way and use some USB charger and connect 5V directly to ESP32 module. Than connect boiler wires to turn on/off heating to relay switch module (to Normally open connector).
